// Generated by CIRCT firtool-1.62.0
module DigitalLDOLogic(
  input        clock,
               reset,
               io_in,
               io_inb,
  output [3:0] io_out
);

  reg [3:0] lastVoltage;
  always @(posedge clock) begin
    if (reset)
      lastVoltage <= 4'hF;
    else
      lastVoltage <= ~(lastVoltage + {3'h0, io_in} - {3'h0, io_inb});
  end // always @(posedge)
  assign io_out = lastVoltage;
endmodule

